"""This module associates capture file headers with parser modules."""

from enum import Enum
from typing import Callable

from formats.afterburner import Afterburner
from formats.frameview import FrameView
from formats.fraps import FRAPS
from formats.gpuz import GPUZ
from formats.hwinfo import HWiNFO
from formats.ldat import LDAT
from formats.ocat import OCAT
from formats.pcat import PCAT
from formats.precision import Precision
from formats.verbatim import Verbatim


class Format(Enum):
    """Symbols used for creating concrete products."""

    # Discrete capture file formats
    FrameView = ("FrameView", FrameView)
    OCAT = ("OCAT", OCAT)
    FRAPS = ("FRAPS", FRAPS)
    HWiNFO = ("HWiNFO", HWiNFO)
    GPUZ = ("GPU-Z", GPUZ)
    Afterburner = ("MSI Afterburner", Afterburner)
    Precision = ("EVGA Precision X", Precision)
    PCAT = ("PCAT", PCAT)
    LDAT = ("LDAT", LDAT)

    # Fallback
    Verbatim = ("Verbatim", Verbatim)

    def app_name(self) -> str:
        """Return a string of the application name (e.g., FrameView) for a log file."""
        return self.value[0]

    @property
    def parser(self) -> Callable:
        """Return the parser module for a log file."""
        return self.value[1]


# App/version-specific headers for determining capture file type. Matching a set of strings will be
# more accurate but may be difficult for logs with optional headers (e.g., MSI Afterburner, HWiNFO)
# When adding a new version, headers must be enclosed within a set of parenthesis and include at
# least one comma, even if only testing for one header. Example: "1.0": ("Time",)
capture_fingerprints: dict[Format, dict[str, set]] = {
    Format.FrameView: {
        "1.0": {
            "Application",
            "SwapChainAddress",
            "Runtime",
            "SyncInterval",
            "PresentFlags",
            "AllowsTearing",
            "PresentMode",
            "Dropped",
            "TimeInSeconds",
            "MsBetweenPresents",
            "MsBetweenDisplayChangeActual",
            "MsUntilRenderComplete",
            "MsUntilDisplayed",
            "GPUOnlyPower(W)",
            "TotalMinusUSBCPower(W)",
            "TotalPower(W)",
            "AMDPower(W)",
            "PerfPerWattGPUOnly(F/J)",
            "PerfPerWattTotalMinusUSBC(F/J)",
            "PerfPerWattTotal(F/J)",
            "PerfPerWattAMD(F/J)",
        },
        "1.1": {
            "Application",
            "GPU",
            "CPU",
            "Resolution",
            "Runtime",
            "AllowsTearing",
            "ProcessID",
            "SwapChainAddress",
            "SyncInterval",
            "PresentFlags",
            "PresentMode",
            "Dropped",
            "TimeInSeconds",
            "MsBetweenPresents",
            "MsBetweenDisplayChange",
            "MsInPresentAPI",
            "MsRenderPresentLatency",
            "MsUntilDisplayed",
            "Render Queue Depth",
            "GPU0Clk(MHz)",
            "GPU0Util(%)",
            "GPU0Temp(C)",
            "GPU1Clk(MHz)",
            "GPU1Util(%)",
            "GPU1Temp(C)",
            "PCAT Power Total(W)",
            "Perf/W Total(F/J) (PCAT)",
            "Perf/W Total(F/J) (API)",
            "Perf/W GPUOnly(F/J) (API)",
            "Perf/W Total-USBC(F/J) (API)",
            "GPUOnlyPwr(W) (API)",
            "NV-Total-USBCPwr(W) (API)",
            "NV Pwr(W) (API)",
            "AMDPwr(W) (API)",
            "CPUClk(MHz)",
            "CPUUtil(%)",
            "CPU Package Temp(C)",
            "CPU Package Power(W)",
            "CPU TDP (W)",
            "CPUCoreUtil%[ 0]",
            # "CPUCoreUtil%[1-63]",
        },
        "1.2": {
            "Application",
            "GPU",
            "CPU",
            "Resolution",
            "Runtime",
            "AllowsTearing",
            "ProcessID",
            "SwapChainAddress",
            "SyncInterval",
            "PresentFlags",
            "PresentMode",
            "Dropped",
            "TimeInSeconds",
            "MsBetweenPresents",
            "MsBetweenDisplayChange",
            "MsInPresentAPI",
            "MsRenderPresentLatency",
            "MsUntilDisplayed",
            "Render Queue Depth",
            "GPU0Clk(MHz)",
            "GPU0Util(%)",
            "GPU0Temp(C)",
            "GPU0MemClk(MHz)",
            "GPU1Clk(MHz)",
            "GPU1Util(%)",
            "GPU1Temp(C)",
            "GPU1MemClk(MHz)",
            "PCAT Power Total(W)",
            "Perf/W Total(F/J) (PCAT)",
            "Perf/W Total(F/J) (API)",
            "Perf/W GPUOnly(F/J) (API)",
            "Perf/W Total-USBC(F/J) (API)",
            "GPUOnlyPwr(W) (API)",
            "NV-Total-USBCPwr(W) (API)",
            "NV Pwr(W) (API)",
            "AMDPwr(W) (API)",
            "CPUClk(MHz)",
            "CPUUtil(%)",
            "CPU Package Temp(C)",
            "CPU Package Power(W)",
            "CPU TDP (W)",
            "CPUCoreUtil%[ 0]",
            # "CPUCoreUtil%[1-63]",
            "Current Battery Capacity(Wh)",
            "Total Battery Capacity(Wh)",
            "Battery Percentage",
            "Battery Drain Rate(W)",
        },
        "1.4": {
            "Application",
            "GPU",
            "CPU",
            "Resolution",
            "Runtime",
            "AllowsTearing",
            "ProcessID",
            "SwapChainAddress",
            "SyncInterval",
            "PresentFlags",
            "PresentMode",
            "Dropped",
            "TimeInSeconds",
            "MsBetweenPresents",
            "MsBetweenDisplayChange",
            "MsInPresentAPI",
            "MsRenderPresentLatency",
            "MsUntilDisplayed",
            "Render Queue Depth",
            "MsPCLatency",
            "GPU0Clk(MHz)",
            "GPU0Util(%)",
            "GPU0Temp(C)",
            "GPU0MemClk(MHz)",
            "GPU1Clk(MHz)",
            "GPU1Util(%)",
            "GPU1Temp(C)",
            "GPU1MemClk(MHz)",
            "PCAT Power Total(W)",
            "Perf/W Total(F/J) (PCAT)",
            "Perf/W Total(F/J) (API)",
            "Perf/W GPUOnly(F/J) (API)",
            "Perf/W Total-USBC(F/J) (API)",
            "GPUOnlyPwr(W) (API)",
            "NV-Total-USBCPwr(W) (API)",
            "NV Pwr(W) (API)",
            "AMDPwr(W) (API)",
            "CPUClk(MHz)",
            "CPUUtil(%)",
            "CPU Package Temp(C)",
            "CPU Package Power(W)",
            "CPU TDP (W)",
            "CPUCoreUtil%[ 0]",
            # "CPUCoreUtil%[1-63]",
            "Current Battery Capacity(Wh)",
            "Total Battery Capacity(Wh)",
            "Battery Percentage",
            "Battery Drain Rate(W)",
        },
    },
    Format.OCAT: {
        "1.6.1": {
            "Application",
            "ProcessID",
            "SwapChainAddress",
            "Runtime",
            "SyncInterval",
            "PresentFlags",
            "AllowsTearing",
            "PresentMode",
            "WasBatched",
            "DwmNotified",
            "Dropped",
            "TimeInSeconds",
            "MsBetweenPresents",
            "MsBetweenDisplayChange",
            "MsInPresentAPI",
            "MsUntilRenderComplete",
            "MsUntilDisplayed",
            "MsEstimatedDriverLag",
            "Width",
            "Height",
            "Motherboard",
            "OS",
            "Processor",
            "System RAM",
            "Base Driver Version",
            "Driver Package",
            "GPU #",
            "GPU",
            "GPU Core Clock (MHz)",
            "GPU Memory Clock (MHz)",
            "GPU Memory (MB)",
        },
    },
    Format.FRAPS: {
        "3.5.99": {"Frame", "Time (ms)"},
    },
    Format.PCAT: {
        "Release": {
            "timestamp",
            "sys_timestamp",
            "w_total",
            "pex_12v1_v",
            "pex_12v1_a",
            "pex_12v1_w",
            "pex_12v2_v",
            "pex_12v2_a",
            "pex_12v2_w",
            "slot_12v_v",
            "slot_12v_a",
            "slot_12v_w",
            "slot_3v3_v",
            "slot_3v3_a",
            "slot_3v3_w",
            "slot_aux_v",
            "slot_aux_a",
            "slot_aux_w",
        },
    },
    Format.LDAT: {
        "1.0": {
            "0",
        }
    },
    Format.HWiNFO: {
        "7.14": {
            "+12V [V]",
            "+3.3V [V]",
            "+5V [V]",
            "3VSB [V]",
            "AVCC3 [V]",
            "Average Effective Clock [MHz]",
            "Bus Clock [MHz]",
            "Chassis Intrusion [Yes/No]",
            "CLR (CBo/LLC/Ring) OC Ratio Limit [x]",
            "CLR (CBo/LLC/Ring) Voltage Offset [V]",
            "Command Rate [T]",
            "Core 0 [°C]",
            "Core 0 C7 Residency [%]",
            "Core 0 Clock [MHz]",
            "Core 0 Critical Temperature [Yes/No]",
            "Core 0 Distance to TjMAX [°C]",
            "Core 0 Power Limit Exceeded [Yes/No]",
            "Core 0 Ratio [x]",
            "Core 0 T0 C0 Residency [%]",
            "Core 0 T0 Effective Clock [MHz]",
            "Core 0 T0 Usage [%]",
            "Core 0 Thermal Throttling [Yes/No]",
            "Core 0 VID [V]",
            "Core C0 Residency (avg) [%]",
            "Core C7 Residency (avg) [%]",
            "Core Clocks (avg) [MHz]",
            "Core Critical Temperature (avg) [Yes/No]",
            "Core Distance to TjMAX (avg) [°C]",
            "Core Effective Clocks (avg) [MHz]",
            "Core Max [°C]",
            "Core Power Limit Exceeded (avg) [Yes/No]",
            "Core Ratios (avg) [x]",
            "Core Temperatures (avg) [°C]",
            "Core Thermal Throttling (avg) [Yes/No]",
            "Core Usage (avg) [%]",
            "Core VIDs (avg) [V]",
            "CPU [°C]",
            "CPU [RPM]",
            "CPU GT Cores (Graphics) [°C]",
            "CPU IA Cores [°C]",
            "CPU Package [°C]",
            "CPU Package Power [W]",
            "Current (IIN) [A]",
            "Current (IOUT) [A]",
            "Current cTDP Level []",
            "Current DL rate [KB/s]",
            "Current UP rate [KB/s]",
            "Date",
            "DDR [V]",
            "DDR VPP [V]",
            "DDR VTT [V]",
            "Drive Airflow Temperature [°C]",
            "Drive Failure [Yes/No]",
            "Drive Remaining Life [%]",
            "Drive Temperature [°C]",
            "Drive Warning [Yes/No]",
            "GPU 8-pin #1 Input Power [W]",
            "GPU 8-pin #1 Input Voltage [V]",
            "GPU Bus Load [%]",
            "GPU Clock [MHz]",
            "GPU Core Load [%]",
            "GPU Core Voltage [V]",
            "GPU D3D Memory Dedicated [MB]",
            "GPU D3D Memory Dynamic [MB]",
            "GPU D3D Usage [%]",
            "GPU D3D Usages (avg) [%]",
            "GPU Effective Clock [MHz]",
            "GPU Fan1 [%]",
            "GPU Fan1 [RPM]",
            "GPU GT Usage [%]",
            "GPU Hot Spot Temperature [°C]",
            "GPU Input PP Source Power (sum) [W]",
            "GPU Media Engine Usage [%]",
            "GPU Memory Allocated [MB]",
            "GPU Memory Clock [MHz]",
            "GPU Memory Controller Load [%]",
            "GPU Memory Junction Temperature [°C]",
            "GPU Memory Usage [%]",
            "GPU Misc0 Input Power [W]",
            "GPU Misc0 Input Voltage [V]",
            "GPU PCIe +12V Input Power [W]",
            "GPU PCIe +12V Input Voltage [V]",
            "GPU Performance Limits (avg) [Yes/No]",
            "GPU Power [W]",
            "GPU Rail Powers (avg) [W]",
            "GPU Rail Voltages (avg) [V]",
            "GPU SRAM Input Power (sum) [W]",
            "GPU SRAM Output Power [W]",
            "GPU SRAM Output Voltage [V]",
            "GPU Temperature [°C]",
            "GPU Video Clock [MHz]",
            "GPU Video Decode 0 Usage [%]",
            "GPU Video Encode 0 Usage [%]",
            "GPU Video Engine Load [%]",
            "GPU VR Usage [%]",
            "GT (Slice) Voltage Offset [V]",
            "GT (Unslice) Voltage Offset [V]",
            "GT Limit Reasons (avg) [Yes/No]",
            "GT: DDR RAPL [Yes/No]",
            "GT: Domain-Level PBM PLGT [Yes/No]",
            "GT: Fuses limit [Yes/No]",
            "GT: Inefficient Operation [Yes/No]",
            "GT: Max VR Voltage, ICCmax, PL4 [Yes/No]",
            "GT: Package-Level RAPL/PBM PL1 [Yes/No]",
            "GT: Package-Level RAPL/PBM PL2, PL3 [Yes/No]",
            "GT: PROCHOT [Yes/No]",
            "GT: Residency State Regulation [Yes/No]",
            "GT: Running Average Thermal Limit [Yes/No]",
            "GT: Thermal Event [Yes/No]",
            "GT: VR TDC [Yes/No]",
            "GT: VR Thermal Alert [Yes/No]",
            "IA Cores Power [W]",
            "IA Limit Reasons (avg) [Yes/No]",
            "IA OC Ratio Limit [x]",
            "IA Voltage Offset [V]",
            "IA: DDR RAPL [Yes/No]",
            "IA: Electrical Design Point/Other (ICCmax, PL4, SVID, DDR RAPL) [Yes/No]",
            "IA: Max Turbo Limit [Yes/No]",
            "IA: Package-Level RAPL/PBM PL1 [Yes/No]",
            "IA: Package-Level RAPL/PBM PL2, PL3 [Yes/No]",
            "IA: PCS (PECI) [Yes/No]",
            "IA: PROCHOT [Yes/No]",
            "IA: Residency State Regulation [Yes/No]",
            "IA: Running Average Thermal Limit [Yes/No]",
            "IA: Thermal Event [Yes/No]",
            "IA: Thermal Velocity Boost [Yes/No]",
            "IA: Turbo Attenuation (MCT) [Yes/No]",
            "IA: VmaxStress [Yes/No]",
            "IA: VR TDC [Yes/No]",
            "IA: VR Thermal Alert [Yes/No]",
            "Max CPU/Thread Usage [%]",
            "Memory Clock [MHz]",
            "Memory Clock Ratio [x]",
            "Noise sensor [dB]",
            "OC Ratio Limits (avg) [x]",
            "On-Demand Clock Modulation [%]",
            "Package/Ring Critical Temperature [Yes/No]",
            "Package/Ring Power Limit Exceeded [Yes/No]",
            "Package/Ring Thermal Throttling [Yes/No]",
            "Page File Usage [%]",
            "PCH [°C]",
            "PCH Core [V]",
            "PCIe Link Speed [GT/s]",
            "PCIEX16 [°C]",
            "PCIEX8 [°C]",
            "Performance Limit - Max Operating Voltage [Yes/No]",
            "Performance Limit - Power [Yes/No]",
            "Performance Limit - Reliability Voltage [Yes/No]",
            "Performance Limit - Thermal [Yes/No]",
            "Performance Limit - Utilization [Yes/No]",
            "Physical Memory Available [MB]",
            "Physical Memory Load [%]",
            "Physical Memory Used [MB]",
            "PL1 Power Limit [W]",
            "PL2 Power Limit [W]",
            "Power (Input) [W]",
            "Power (POUT) [W]",
            "Read Activity [%]",
            "Read Rate [MB/s]",
            "Read Total [MB]",
            "Rest-of-Chip Power [W]",
            "Ring Limit Reasons (avg) [Yes/No]",
            "Ring/LLC Clock [MHz]",
            "RING: DDR RAPL [Yes/No]",
            "RING: Max VR Voltage, ICCmax, PL4 [Yes/No]",
            "RING: Package-Level RAPL/PBM PL1 [Yes/No]",
            "RING: Package-Level RAPL/PBM PL2, PL3 [Yes/No]",
            "RING: PROCHOT [Yes/No]",
            "RING: Residency State Regulation [Yes/No]",
            "RING: Running Average Thermal Limit [Yes/No]",
            "RING: Thermal Event [Yes/No]",
            "RING: VR TDC [Yes/No]",
            "RING: VR Thermal Alert [Yes/No]",
            "System Agent Clock [MHz]",
            "System1 [°C]",
            "Tcas [T]",
            "Time",
            "Total Activity [%]",
            "Total CPU Usage [%]",
            "Total DL [MB]",
            "Total Errors []",
            "Total GPU Power (normalized) [% of TDP] [%]",
            "Total GPU Power [% of TDP] [%]",
            "Total Host Reads [GB]",
            "Total Host Writes [GB]",
            "Total UP [MB]",
            "Tras [T]",
            "Trc [T]",
            "Trcd [T]",
            "Trfc [T]",
            "Trp [T]",
            "Uncore/SA Voltage Offset [V]",
            "VBAT [V]",
            "VCCIO [V]",
            "VCCSA [V]",
            "Vcore [V]",
            "Virtual Memory Available [MB]",
            "Virtual Memory Committed [MB]",
            "Virtual Memory Load [%]",
            "Voltage Offsets (avg) [V]",
            "VR Loop1 [°C]",
            "VR VCC Temperature (SVID) [°C]",
            "VR VIN [V]",
            "VR VOUT [V]",
            "VRM MOS [°C]",
            "Write Activity [%]",
            "Write Rate [MB/s]",
            "Write Total [MB]",
        }
    },
    Format.GPUZ: {
        "2.0": {
            "Date",
            "GPU Clock [MHz]",
            "Memory Clock [MHz]",
            "GPU Temperature [°C]",
            "Fan 1 Speed (%) [%]",
            "Fan 1 Speed (RPM) [RPM]",
            "Memory Used [MB]",
            "GPU Load [%]",
            "Memory Controller Load [%]",
            "Video Engine Load [%]",
            "Bus Interface Load [%]",
            "Board Power Draw [W]",
            "GPU Chip Power Draw [W]",
            "MVDDC Power Draw [W]",
            "PWR_SRC Power Draw [W]",
            "PWR_SRC Voltage [V]",
            "PCIe Slot Power [W]",
            "PCIe Slot Voltage [V]",
            "8-Pin #1 Power [W]",
            "8-Pin #1 Voltage [V]",
            "Power Consumption (%) [% TDP]",
            "PerfCap Reason []",
            "GPU Voltage [V]",
            "CPU Temperature [°C]",
            "System Memory Used [MB]",
        }
    },
    Format.Afterburner: {
        "4.6.4": {
            "02",
            "BUS usage",
            "Commit charge",
            "Core clock",
            "CPU clock",
            "CPU power",
            "CPU temperature",
            "CPU usage",
            "CPU1 clock",
            "CPU1 temperature",
            "CPU1 usage",
            "Fan speed",
            "Fan tachometer",
            "FB usage",
            "Framerate 0.1% Low",
            "Framerate 1% Low",
            "Framerate Avg",
            "Framerate Max",
            "Framerate Min",
            "Framerate",
            "Frametime",
            "GPU temperature",
            "GPU usage",
            "GPU voltage",
            "Memory clock",
            r"Memory usage \ process",
            "Memory usage",
            "No load limit",
            "Power limit",
            "Power percent",
            "Power",
            r"RAM usage \ process",
            "RAM usage",
            "Temp limit",
            "VID usage",
            "Voltage limit",
        }
    },
    Format.Precision: {
        "1.0.7": {
            "02",
            "BUS Usage",
            "FB Usage",
            "Framerate",
            "Frametime",
            "GPU Clock",
            "GPU Fan 1 Speed",
            "GPU Fan 1 Tacho",
            "GPU Fan Ext Speed",
            "GPU Fan Ext Tacho",
            "GPU Memory Clock",
            "GPU Temperature",
            "GPU Usage",
            "GPU Voltage",
            "Memory Usage",
            "No Load Limit",
            "Normalized Total Power",
            "Power Limit",
            "Temp Limit",
            "Total Power",
            "VID Usage",
            "Voltage Limit",
        }
    },
}
